name: Build CI

on:
  push:
    tags-ignore:
      - "**"
    branches:
      - develop

defaults:
  run:
    working-directory: app

jobs:
  deploy:
    if: contains(github.event.head_commit.message, 'skip ci') == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Install dependencies
        run: yarn install
      - name: Build app
        run: next build
